import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft } from "lucide-react";

import { AnalysisLoader } from "@/components/analysis-loader";
import { MotionFadeIn } from "@/components/motion-fade-in";
import { PaletteProvider } from "@/components/palette-provider";
import { SongPlayer } from "@/components/player/song-player";
import { SpotifyPlayerProvider } from "@/components/player/spotify-player-provider";
import { SongHero } from "@/components/song-hero";
import { getCachedAnalysis } from "@/lib/cache";
import { PROMPT_VERSION } from "@/lib/schemas";
import { getTrack } from "@/lib/spotify";

export const dynamic = "force-dynamic";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ id: string }>;
}): Promise<Metadata> {
  const { id } = await params;
  try {
    const track = await getTrack(id);
    const artist = track.artists.map((a) => a.name).join(", ");
    const title = `${track.name} — ${artist}`;
    const trackKey = track.external_ids?.isrc ?? track.id;
    const analysis = await getCachedAnalysis(trackKey, PROMPT_VERSION);
    const description =
      analysis?.summary ??
      `What ${track.name} by ${artist} is actually about — themes, line-by-line meaning, and references.`;
    return {
      title,
      description,
      // Open Graph image is generated by ./opengraph-image.tsx — leaving
      // `images` unset here lets the file-based metadata route take over.
      openGraph: {
        title,
        description,
        type: "article",
      },
      twitter: {
        card: "summary_large_image",
        title,
        description,
      },
    };
  } catch {
    return { title: "Song" };
  }
}

export default async function SongPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;

  let track;
  try {
    track = await getTrack(id);
  } catch (err) {
    const message = err instanceof Error ? err.message : "Spotify error";
    // 400/404 from Spotify means the ID is bad — route to not-found instead
    // of showing a generic error card.
    if (/\b(400|404)\b/.test(message)) notFound();
    return (
      <main className="mx-auto max-w-3xl px-6 py-16">
        <BackLink />
        <div className="mt-8 rounded-lg border border-[color:var(--color-border)] bg-[color:var(--color-card)] p-6">
          <h1 className="text-xl font-semibold">Could not load this song</h1>
          <p className="mt-2 text-sm text-[color:var(--color-muted-foreground)]">
            {message}
          </p>
          <p className="mt-4 text-xs text-[color:var(--color-muted-foreground)]">
            Make sure SPOTIFY_CLIENT_ID and SPOTIFY_CLIENT_SECRET are set in
            .env.local.
          </p>
        </div>
      </main>
    );
  }

  if (!track) notFound();

  const heroImage = track.album.images[0]?.url ?? null;
  const releaseYear = track.album.release_date.slice(0, 4);
  const artistDisplay = track.artists.map((a) => a.name).join(", ");

  return (
    <PaletteProvider imageUrl={heroImage}>
      <SpotifyPlayerProvider spotifyId={track.id}>
      <main className="mx-auto max-w-6xl px-6 py-12">
        <BackLink />

        <div className="mt-8">
          <SongHero
            trackKey={track.external_ids?.isrc ?? track.id}
            spotifyId={track.id}
            name={track.name}
            artist={artistDisplay}
            album={track.album.name}
            releaseYear={releaseYear}
            imageUrl={heroImage}
          />
        </div>

        <MotionFadeIn
          delay={0.15}
          className="mt-10 grid gap-8 lg:grid-cols-[1fr_340px] lg:items-start"
        >
          <div className="min-w-0">
            <AnalysisLoader
              id={track.id}
              title={track.name}
              artist={artistDisplay}
            />
          </div>
          <aside className="order-first lg:order-last lg:sticky lg:top-[22rem]">
            <SongPlayer />
          </aside>
        </MotionFadeIn>
      </main>
      </SpotifyPlayerProvider>
    </PaletteProvider>
  );
}

function BackLink() {
  return (
    <Link
      href="/"
      className="inline-flex items-center gap-1.5 text-sm text-[color:var(--color-muted-foreground)] transition-colors hover:text-[color:var(--color-foreground)]"
    >
      <ArrowLeft className="h-4 w-4" aria-hidden />
      Back
    </Link>
  );
}
